# GameCube disc image bi2 data, located at 0x440 in the disc.
# Generated by splat.

.section .data

debug_monitor_size: .long 0x00000000
simulated_memory_size: .long 0x00000000

argument_offset: .long 0x00000000

debug_flag: .long 0x00000000

track_offset: .long 0x00000000
track_size: .long 0x00000000

country_code_bi2: .long 0x00000001

ukn_int_bi2: .long 0x00000001
ukn_int_bi2_2: .long 0x00000001

.fill 0x00001FDC

