# GameCube disc image boot data, located at 0x00 in the disc.
# Generated by splat.

.section .data

system_code: .ascii "G"
game_code: .ascii "LM"
region_code: .ascii "E"
publisher_code: .ascii "01"

disc_id: .byte 0
game_version: .byte 0
audio_streaming: .byte 0
stream_buffer_size: .byte 0

.fill 0x12

gc_magic: .long 0xC2339F3D

game_name: .ascii "LUIGI'S MANSION"
.org 0x400

apploader_size: .long 0x0001310C

debug_monitor_address: .long 0x80280060

.fill 0x18

dol_offset: .long 0x00015600
fst_offset: .long 0x003B5100

# The FST is only allocated once per game boot, even in games with multiple disks. fst_max_size is used to ensure that
# there is enough space allocated for the FST in the event that a game spans multiple disks, and one disk has a larger FST than another.
fst_size: .long 0x00005179
fst_max_size: .long 0x00005179

# Not even YAGCD knows what these are for.
user_position: .long 0x803FAE80
user_length: .long 0x003C0000
unk_int: .long 0x56C98000

.word 0
